### ISSUE TITLE
JavaScripts from vendors should include a version number

### ISSUE THREAD

**Issue by tombye** [alphagov/digitalmarketplace-frontend-toolkit#16]
While we don't enforce a method of dependancy management, it should be made clear the versions of all vendor code we use so projects can guarantee toolkit code will work.

This was originally raised in https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/12#issuecomment-69334911

**Comment by quis** [comment]
Should have done this! https://github.com/blog/1506-closing-issues-via-pull-requests
