### ISSUE TITLE
Links on the forms page 404

### ISSUE THREAD

**Issue by quis** [alphagov/digitalmarketplace-frontend-toolkit#311]
http://alphagov.github.io/digitalmarketplace-frontend-toolkit/forms/

links to:
- http://alphagov.github.io/forms/selection-buttons.html
- http://alphagov.github.io/forms/list-entry.html
- etc…

**Comment by pcraig3** [comment]
Also there's no way to get back to the index page from the forms page.

**Comment by pcraig3** [comment]
Hey @quis.

https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/323

**Comment by carolinegreen** [comment]
Think this is fixed, the links now work so closing this.
