### ISSUE TITLE
Option select broken for long labels/narrow widths

### ISSUE THREAD

**Issue by TheDoubleK** [alphagov/digitalmarketplace-frontend-toolkit#346]
The label spills out of the option-select container, so words can be cut off or obscured altogether.
e.g. 
![screen shot 2017-05-15 at 09 22 36](https://cloud.githubusercontent.com/assets/6525554/26144700/cac82a1a-3ae1-11e7-8fdf-5260696a8ee7.png)

And here showing the overspilling label:
![screen shot 2017-05-16 at 15 18 45](https://cloud.githubusercontent.com/assets/6525554/26144757/f988e7f4-3ae1-11e7-8caf-47cd088f0860.png)

This is going to become more of an issue with G-Cloud 9 service filters, as many more long filter names are being introduced.

It looks like this is a wider issue with the GOV.UK option select style - e.g. the same problem can be seen on this page: https://www.gov.uk/cma-cases - so if we come up with a fix it would be nice to make a pull-request on the GOV.UK styles at the same time too.

The issue can't easily be seen in our toolkit example page (http://alphagov.github.io/digitalmarketplace-frontend-toolkit/forms/option-select.html) because none of the example labels are long enough to wrap in the full-width option select, but if you tweak the examples to have really long labels you can see it's broken here:
![screen shot 2017-05-17 at 09 24 35](https://cloud.githubusercontent.com/assets/6525554/26144987/b20bcc1a-3ae2-11e7-9726-26fb4903a48e.png)

**Comment by galund** [comment]
deployed to preview already with <https://trello.com/c/IrcO0G3U/491-add-clear-all-filters-link>
